# Generated by Django 2.1.5 on 2019-02-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_trymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
